spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbsec
    username: user
    password: *****
  jpa:
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true